apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  startingDeadlineSeconds: 15
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
          - name: django-app
            image: hardrope/web:latest
            imagePullPolicy: IfNotPresent
            command: ["python3", "manage.py", "clearsessions"]
            envFrom:
            - configMapRef:
                name: django-config
          restartPolicy: OnFailure