apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  ttlSecondsAfterFinished: 50
  template:
    spec:
      containers:
      - name: django-app
        image: hardrope/web:latest
        command: ["python3", "manage.py", "migrate", "--no-input"]
        envFrom:
            - secretRef:
                name: django-secret
      restartPolicy: OnFailure